#!/bin/bash -x

cd /home/john/thermy
git clone https://github.com/thompsonline/thermostat-control -b master
cd thermostat-control
git pull

cd /home/john/thermy
git clone https://github.com/thompsonline/thermostat-display -b master
cd thermostat-display
git pull

cd /home/john/thermy
git clone https://github.com/thompsonline/thermostat-plotter -b master
cd thermostat-plotter
git pull

cd /home/john/thermy
git clone https://github.com/thompsonline/thermostat-rebootmonitor -b master
cd thermostat-rebootmonitor
git pull

cd /home/john/thermy
git clone https://github.com/thompsonline/thermostat-monitorwifi -b master
cd thermostat-monitorwifi
git pull

cd /home/john/thermy
git clone https://github.com/thompsonline/thermy-autoupdate -b master
cd thermy-autoupdate
git pull

cd /home/john/thermy
git clone https://github.com/thompsonline/thermostat-localsensor -b master
cd thermostat-localsensor
git pull

cd /home/john/thermy
git clone https://github.com/thompsonline/thermostat-cleanup -b master
cd thermostat-cleanup
git pull

cd /home/john/thermy
git clone https://github.com/thompsonline/thermostat-savesensor -b master
cd thermostat-savesensor
git pull
mkdir /var/www/html/remotesensor
#cp savesensor.php /var/www/html/remotesensor/

cd /home/john/thermy
git clone https://github.com/thompsonline/thermostat-eventlogger -b master
cd thermostat-eventlogger
git pull
mkdir /var/www/html/eventlogger
#cp savesensor.php /var/www/html/remotesensor/


